[general]
import = [
  "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[font]
size = 14

[font.normal]
family = "Iosevka Term"
style = "Regular"

[env]
TERM = "xterm-256color"

[terminal]
shell = "/bin/zsh"

[window.padding]
x = 4
y = 4

