[general]

import = [
  "~/.config/alacritty/themes/gruvbox.toml"
]

[font]

size = 22

[font.normal]

family = "Iosevka Term"
style = "Regular"

[env]

TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]

padding.x = 4
padding.y = 4

dynamic_padding = false

opacity = 0.9
blur = true
