[general]

import = [
  "~/.config/alacritty/theme.toml"
]

[font]

size = 14

[font.normal]

family = "Iosevka Term"
style = "Regular"

[env]

TERM = "xterm-256color"

[window.padding]

x = 4
y = 4

