# Gruvbox Dark mode Palette
# https://github.com/morhetz/gruvbox?tab=readme-ov-file#dark-mode-1

[colors.primary]

background = "#1d2021"
foreground = "#d4be98"

[colors.normal]

black   = "#282828"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#d4be98"

[colors.bright]

black   = "#504945"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#d4be98"
